name: Angular Build

on:
  push:
    branches:
      - main
      - dev
      - feat/*
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build Angular project
        run: npm run build --if-present
        working-directory: frontend
